"use strict";
var React = require('react');
var ReactRouter = require('react-router');
var Main_1 = require('../Main');
var TodoList_1 = require('../components/TodoList');
var TodoModel_1 = require('../models/TodoModel');
var Router = ReactRouter.Router;
var Route = ReactRouter.Route;
var hashHistory = ReactRouter.hashHistory;
var IndexRoute = ReactRouter.IndexRoute;
var model = new TodoModel_1.TodoModel('react-todos');
var routes = (React.createElement(Router, {history: hashHistory}, React.createElement(Route, {path: '/', component: Main_1.Main}, React.createElement(IndexRoute, {component: TodoList_1.TodoList, model: model}))));
exports.routes = routes;
